config/routes.rb
Rails.application.routes.draw do
  resources :order_items
  get 'cart', to: 'cart#show'
  resources :categories
  resources :products
  devise_for :users
  root to: "pages#home"
  get 'shop', to: 'shop#index'
  get 'about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  def subtotal
    order_items.collect { |order_item| order_item.valid? ? order_item.budget * order_item.quantity : 0 }.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_budget
  before_save :set_total

  def budget
    # If there is a record
    if persisted?
      self[:budget]
    else
      product.min_price
    end
  end

  def total
    budget * quantity
  end

  private

  def set_budget
    self[:budget] = budget
  end

  def set_total
    self[:total] = total * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :image
  has_many :order_items
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  before_action :authenticate_user!
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:heading, :body, :display, :order)
    end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :set_order

  def create
    @order_item = @order.order_items.new(order_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_params)
    @order_items = current_order.order_items
  end

  def destroy
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = current_order.order_items
  end

  private

  def order_params
    params.require(:order_item).permit(:product_id, :quantity)
  end

  def set_order
    @order = current_order
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :info ]

  def home
    @page = 'home'
  end

  def shop
    @page = 'shop'
  end

  def about
    @page = 'about'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @product.category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :min_price, :image, :available, :category_id)
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  before_action :set_cats
  def index
    @page = 'shop'
    @products = Product.all
    @order_items = current_order.order_items.new
  end

  private

  def set_cats
    @cats = Category.all.where(display: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    # Use Find by id to avoid potential errors
    if Order.find_by_id(session[:order_id]).nil?
      Order.new
    else
      Order.find_by_id(session[:order_id])
    end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/cart/_cart.html.erb
<%= link_to "#{current_order.order_items.size} items with a value of $#{current_order.subtotal}", cart_path %>

app/views/cart/_cart_items.html.erb
<% @order_items.each do |item| %>
  <h3><%= item.product.name  %></h3>
  <%# ## à changer pour afficher le budget %>
  <h3><%= item.product.min_price %></h3>
  <%= form_with model: item do |f|%>
    <%= f.hidden_field :product_id, value: item.product.id %>
    <%= f.number_field :quantity, value: item.quantity.to_i%>
    <%= f.submit "Update Cart" %>
    <%= link_to "Remove Items", item, method: :delete, remote: true %>
  <% end%>
  <h2>Subtotal: <%= item.total %></h2>
<% end %>
<h3>Your current order has a total of: <%= current_order.subtotal %></h3>

app/views/cart/show.html.erb
<div id="cart-item">
    <%= render 'cart_items'%>
</div>

<hr>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Heading:</strong>
    <%= category.heading %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= category.body %>
  </p>

  <p>
    <strong>Display:</strong>
    <%= category.display %>
  </p>

  <p>
    <strong>Order:</strong>
    <%= category.order %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :heading %>
    <%= f.input :body %>
    <%= f.input :display %>
    <%= f.input :order %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/layouts/_links.html.erb
<div class="col-2">
  <h5 class="link-container">
    <%= link_to "Home", root_path, class: "link #{@page == 'home' ? 'active' : ''}"  %>
  </h5>
  <h5 class="link-container">
    <%= link_to "La Boutique", shop_path, class: "link #{@page == 'shop' ? 'active' : ''}"  %>
  </h5>
  <h5 class="link-container">
    <%= link_to "A propos", about_path, class: "link #{@page == 'about' ? 'active' : ''}"  %>
  </h5>
</div>

app/views/layouts/_title.html.erb
<div class="title-card">
  <h1 class="title-text">
    Solstice Fleuriste
  </h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Solstice</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
    <div class="<%= @page %>-page">
      <div class="row page-container">
        <%= render 'layouts/links' %>
        <div class="col-8">
          <% unless @page == 'home' %>
            <%= render 'layouts/title'  %>
          <% end %>
          <%= yield %>
        </div>
        <div class="col-2"></div>
      </div>
    </div>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/order_items/create.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");

app/views/order_items/destroy.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/order_items/update.js.erb
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart-item").html("<%= j render 'cart/cart_items' %>");

app/views/pages/home.html.erb
<div class="col-8"></div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
  <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
          <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
      </ul>
  </div>
  <% end %>

  <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
  </div>

  <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
  </div>

  <div class="field">
      <%= form.label :min_price %>
      <%= form.text_field :min_price %>
  </div>

  <div class="field">
      <%= form.label :available %>
      <%= form.check_box :available %>
  </div>

  <div class="field">
      <%= form.label :featured %>
      <%= form.check_box :featured %>
  </div>

  <div class="field">
      <%= form.label :category%>
      <% if @product.category != nil %>
        <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :heading, @product.category.id) %>
      <% else %>
        <%= form.select :category_id, options_from_collection_for_select(Category.all, :id, :heading) %>
      <% end %>
  </div>

  <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
  </div>

  <div class="actions">
      <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Min price:</strong>
    <%= product.min_price %>
  </p>

  <p>
    <strong>Available:</strong>
    <%= product.available %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shop/_products.html.erb
<div class="row">
    <% @cats.each do |cat| %>
      <% if cat.products.where(featured: true).first.image.attached? %>
        <%= image_tag(cat.products.where(featured: true).first.image, class:'img-fluid')%>
      <% end %>
      <div class="col-12">
          <h1 style="text-align:center;"><%= cat.heading %></h1>
          <hr />
      </div>
      <% @products.each do |product| %>
        <% if product.category == cat %>
          <div class="col-4">
            <h5>
              <%= product.name %>
            </h5>
            <p>
              <%= product.description%>
            </p>
            <span><%= product.min_price %></span>
            <%= form_with model: @order_item do |f| %>
              <%= f.hidden_field :product_id, value: product.id %>
              <%= f.number_field :quantity, value: 1, min: 1%>
              <%= f.submit "Add To Cart" %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
</div>

app/views/shop/index.html.erb
<div class="shop-container">
    <div id="menu-products-container">
        <%= render 'shop/products'%>
    </div>
</div>